In [77]:
import pandas as pd

In [78]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [79]:
df = pd.DataFrame(documents, columns=['course', 'section', 'question', 'text'])

In [80]:
df.head()

course                           section  \
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
2  data-engineering-zoomcamp  General course-related questions   
3  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   

                                            question  \
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
2  Course - Can I still join the course after the...   
3  Course - I have registered for the Data Engine...   
4   Course - What can I do before the course starts?   

                                                text  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
2  Yes, even if you don't register, you're still ...  
3  You don't need it. You're accepted. You can al...  
4  You can start by installing and setting up all...

In [81]:
df[df.course == 'data-engineering-zoomcamp'].head()

course                           section  \
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
2  data-engineering-zoomcamp  General course-related questions   
3  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   

                                            question  \
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
2  Course - Can I still join the course after the...   
3  Course - I have registered for the Data Engine...   
4   Course - What can I do before the course starts?   

                                                text  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
2  Yes, even if you don't register, you're still ...  
3  You don't need it. You're accepted. You can al...  
4  You can start by installing and setting up all...

In [82]:
doc_examples = [
    "January course details, register now",
    "Course prerequisites listed in January catalog",
    "Submit January course homework by end of month",
    "Register for January course, no prerequisites",
    "January course setup: Python and Google Cloud"
]

In [83]:
from sklearn.feature_extraction.text import CountVectorizer

In [84]:
cv = CountVectorizer()

In [85]:
cv.fit(doc_examples)

CountVectorizer()

In [86]:
cv.get_feature_names_out()

array(['and', 'by', 'catalog', 'cloud', 'course', 'details', 'end', 'for',
       'google', 'homework', 'in', 'january', 'listed', 'month', 'no',
       'now', 'of', 'prerequisites', 'python', 'register', 'setup',
       'submit'], dtype=object)

In [87]:
names = cv.get_feature_names_out()
names

array(['and', 'by', 'catalog', 'cloud', 'course', 'details', 'end', 'for',
       'google', 'homework', 'in', 'january', 'listed', 'month', 'no',
       'now', 'of', 'prerequisites', 'python', 'register', 'setup',
       'submit'], dtype=object)

In [88]:
X = cv.transform(doc_examples)

In [89]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 32 stored elements and shape (5, 22)>

In [90]:
X.todense()

matrix([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
         0],
        [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
         0],
        [0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
         1],
        [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
         0],
        [1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
         0]])

In [91]:
pd.DataFrame(X.todense())

0   1   2   3   4   5   6   7   8   9   ...  12  13  14  15  16  17  18  \
0   0   0   0   0   1   1   0   0   0   0  ...   0   0   0   1   0   0   0   
1   0   0   1   0   1   0   0   0   0   0  ...   1   0   0   0   0   1   0   
2   0   1   0   0   1   0   1   0   0   1  ...   0   1   0   0   1   0   0   
3   0   0   0   0   1   0   0   1   0   0  ...   0   0   1   0   0   1   0   
4   1   0   0   1   1   0   0   0   1   0  ...   0   0   0   0   0   0   1   

   19  20  21  
0   1   0   0  
1   0   0   0  
2   0   0   1  
3   1   0   0  
4   0   1   0  

[5 rows x 22 columns]

In [92]:
df_doc = pd.DataFrame(X.todense(), columns=names).T
df_doc

0  1  2  3  4
and            0  0  0  0  1
by             0  0  1  0  0
catalog        0  1  0  0  0
cloud          0  0  0  0  1
course         1  1  1  1  1
details        1  0  0  0  0
end            0  0  1  0  0
for            0  0  0  1  0
google         0  0  0  0  1
homework       0  0  1  0  0
in             0  1  0  0  0
january        1  1  1  1  1
listed         0  1  0  0  0
month          0  0  1  0  0
no             0  0  0  1  0
now            1  0  0  0  0
of             0  0  1  0  0
prerequisites  0  1  0  1  0
python         0  0  0  0  1
register       1  0  0  1  0
setup          0  0  0  0  1
submit         0  0  1  0  0

In [93]:
cv = CountVectorizer(stop_words = 'english')
X = cv.fit_transform(doc_examples)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names).T
df_docs

0  1  2  3  4
catalog        0  1  0  0  0
cloud          0  0  0  0  1
course         1  1  1  1  1
details        1  0  0  0  0
end            0  0  1  0  0
google         0  0  0  0  1
homework       0  0  1  0  0
january        1  1  1  1  1
listed         0  1  0  0  0
month          0  0  1  0  0
prerequisites  0  1  0  1  0
python         0  0  0  0  1
register       1  0  0  1  0
setup          0  0  0  0  1
submit         0  0  1  0  0

In [94]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [95]:
cv = TfidfVectorizer(stop_words='english')
X = cv.fit_transform(doc_examples)

names = cv.get_feature_names_out()
names

array(['catalog', 'cloud', 'course', 'details', 'end', 'google',
       'homework', 'january', 'listed', 'month', 'prerequisites',
       'python', 'register', 'setup', 'submit'], dtype=object)

In [96]:
df_docs = pd.DataFrame(X.toarray(), columns=names).T
df_docs.round(2)

0     1     2     3     4
catalog        0.00  0.57  0.00  0.00  0.00
cloud          0.00  0.00  0.00  0.00  0.47
course         0.33  0.27  0.23  0.36  0.23
details        0.69  0.00  0.00  0.00  0.00
end            0.00  0.00  0.47  0.00  0.00
google         0.00  0.00  0.00  0.00  0.47
homework       0.00  0.00  0.47  0.00  0.00
january        0.33  0.27  0.23  0.36  0.23
listed         0.00  0.57  0.00  0.00  0.00
month          0.00  0.00  0.47  0.00  0.00
prerequisites  0.00  0.46  0.00  0.61  0.00
python         0.00  0.00  0.00  0.00  0.47
register       0.56  0.00  0.00  0.61  0.00
setup          0.00  0.00  0.00  0.00  0.47
submit         0.00  0.00  0.47  0.00  0.00

In [97]:
query = "Do I need to know python to sign up for the January course?"

In [98]:
q = cv.transform([query])
q.toarray()

array([[0.        , 0.        , 0.39515588, 0.        , 0.        ,
        0.        , 0.        , 0.39515588, 0.        , 0.        ,
        0.        , 0.829279  , 0.        , 0.        , 0.        ]])

In [99]:
query_dict = dict(zip(names, q.toarray()[0]))
query_dict

{'catalog': np.float64(0.0),
 'cloud': np.float64(0.0),
 'course': np.float64(0.39515588491314224),
 'details': np.float64(0.0),
 'end': np.float64(0.0),
 'google': np.float64(0.0),
 'homework': np.float64(0.0),
 'january': np.float64(0.39515588491314224),
 'listed': np.float64(0.0),
 'month': np.float64(0.0),
 'prerequisites': np.float64(0.0),
 'python': np.float64(0.8292789960182417),
 'register': np.float64(0.0),
 'setup': np.float64(0.0),
 'submit': np.float64(0.0)}

In [100]:
doc_dict = dict(zip(names, X.toarray()[1]))
doc_dict

{'catalog': np.float64(0.5675015398728066),
 'cloud': np.float64(0.0),
 'course': np.float64(0.2704175244456293),
 'details': np.float64(0.0),
 'end': np.float64(0.0),
 'google': np.float64(0.0),
 'homework': np.float64(0.0),
 'january': np.float64(0.2704175244456293),
 'listed': np.float64(0.5675015398728066),
 'month': np.float64(0.0),
 'prerequisites': np.float64(0.45785666908911726),
 'python': np.float64(0.0),
 'register': np.float64(0.0),
 'setup': np.float64(0.0),
 'submit': np.float64(0.0)}

In [101]:
df_qd = pd.DataFrame([query_dict, doc_dict], index=['query', 'doc']).T

In [102]:
df_qd

query       doc
catalog        0.000000  0.567502
cloud          0.000000  0.000000
course         0.395156  0.270418
details        0.000000  0.000000
end            0.000000  0.000000
google         0.000000  0.000000
homework       0.000000  0.000000
january        0.395156  0.270418
listed         0.000000  0.567502
month          0.000000  0.000000
prerequisites  0.000000  0.457857
python         0.829279  0.000000
register       0.000000  0.000000
setup          0.000000  0.000000
submit         0.000000  0.000000

In [103]:
(df_qd['query'] * df_qd['doc']).sum()

np.float64(0.21371415233666782)

In [104]:
X.dot(q.T).toarray()

array([[0.25955955],
       [0.21371415],
       [0.17843726],
       [0.28419115],
       [0.57137158]])

In [105]:
from sklearn.metrics.pairwise import cosine_similarity

In [106]:
cosine_similarity(X,q)

array([[0.25955955],
       [0.21371415],
       [0.17843726],
       [0.28419115],
       [0.57137158]])

In [107]:
df.columns

Index(['course', 'section', 'question', 'text'], dtype='object')

In [108]:
fields = ['section', 'question', 'text']

In [109]:
df['section'].head()

0    General course-related questions
1    General course-related questions
2    General course-related questions
3    General course-related questions
4    General course-related questions
Name: section, dtype: object

In [110]:
transformers = {}
matrices = {}

for field in fields:
    cv = TfidfVectorizer(stop_words='english', min_df = 3)
    X = cv.fit_transform(df[field])

    transformers[field] = cv
    matrices[field] = X

In [111]:
transformers

{'section': TfidfVectorizer(min_df=3, stop_words='english'),
 'question': TfidfVectorizer(min_df=3, stop_words='english'),
 'text': TfidfVectorizer(min_df=3, stop_words='english')}

In [112]:
matrices['text']

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 26463 stored elements and shape (948, 2118)>

In [113]:
query = "I just singned up. Is it too late to join the course?"

In [114]:
q = transformers['text'].transform([query])
score = cosine_similarity(matrices['text'], q).flatten()

In [115]:
mask = (df.course == 'data-engineering-zoomcamp').values
score = score * mask
score[:10]

array([0.3336047 , 0.        , 0.        , 0.1328874 , 0.        ,
       0.        , 0.        , 0.12722114, 0.        , 0.        ])

In [116]:
import numpy as np

In [117]:
idx = np.argsort(-score)[:10]
idx

array([  0,  15,  22,  27,  38, 287,   3,   7, 113,  11])

In [118]:
score[idx]

array([0.3336047 , 0.23530268, 0.22668   , 0.1894954 , 0.16484429,
       0.13921764, 0.1328874 , 0.12722114, 0.1207499 , 0.10830554])

In [119]:
df.iloc[idx].text

0      The purpose of this document is to capture fre...
15     No, late submissions are not allowed. But if t...
22     It's up to you which platform and environment ...
27     You can do most of the course without a cloud....
38     You will have two attempts for a project. If t...
287    This error could result if you are using some ...
3      You don't need it. You're accepted. You can al...
7      Yes, we will keep all the materials after the ...
113    In the join queries, if we mention the column ...
11     No, you can only get a certificate if you fini...
Name: text, dtype: object

In [120]:
query = "I just singned up. Is it too late to join the course?"

In [121]:
boost = {'question': 3.0}

In [122]:
score = np.zeros(len(df))

In [123]:
for f in fields:
    b = boost.get(f, 1.0)
    q = transformers[f].transform([query])
    s = cosine_similarity(matrices[f], q).flatten()
    score = score + b * s

In [124]:
filters = {
    'course': 'data-engineering-zoomcamp'
}
filters

{'course': 'data-engineering-zoomcamp'}

In [125]:
for field, value in filters.items():
    print(f"Field = {field!r}, Value = {value!r}")
    print("  Column sample:", df[field].head().tolist())
    mask = (df[field] == value).values
    print("  Mask sample:", mask[:10])
    score = score * mask

Field = 'course', Value = 'data-engineering-zoomcamp'
  Column sample: ['data-engineering-zoomcamp', 'data-engineering-zoomcamp', 'data-engineering-zoomcamp', 'data-engineering-zoomcamp', 'data-engineering-zoomcamp']
  Mask sample: [ True  True  True  True  True  True  True  True  True  True]


In [126]:
idx = np.argsort(-score)[:10]
results = df.iloc[idx]
results.to_dict(orient='records')

[{'course': 'data-engineering-zoomcamp',
  'section': 'General course-related questions',
  'question': 'Course - What are the prerequisites for this course?',
  'text': 'GitHub - DataTalksClub data-engineering-zoomcamp#prerequisites'},
 {'course': 'data-engineering-zoomcamp',
  'section': 'General course-related questions',
  'question': 'How can we contribute to the course?',
  'text': 'Star the repo! Share it with friends if you find it useful ❣️\nCreate a PR if you see you can improve the text or the structure of the repository.'},
 {'course': 'data-engineering-zoomcamp',
  'section': 'General course-related questions',
  'question': 'Course - Which playlist on YouTube should I refer to?',
  'text': 'All the main videos are stored in the Main “DATA ENGINEERING” playlist (no year specified). The Github repository has also been updated to show each video with a thumbnail, that would bring you directly to the same playlist below.\nBelow is the MAIN PLAYLIST’. And then you refer to the

In [127]:
class TextSearch:
    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params = {}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            cv = TfidfVectorizer(**vectorizer_params)
            X = cv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = cv

    def search(self, query, n_results = 10, boost = {}, filters = {}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s
        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient='records')

In [128]:
fields

['section', 'question', 'text']

In [129]:
index = TextSearch(text_fields=['section', 'question', 'text'])

In [130]:
index.fit(documents)

In [131]:
query

'I just singned up. Is it too late to join the course?'

In [132]:
index.search(
    query='I just singned up. Is it too late to join the course?',
    n_results=5,
    boost={'question': 3.0},
    filters={'course': 'data-engineering-zoomcamp'}
)

[{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineerin

In [133]:
from sklearn.decomposition import TruncatedSVD

In [134]:
X = matrices['text']
cv = transformers['text']

In [135]:
svd = TruncatedSVD(n_components = 16)
X_emb = svd.fit_transform(X)

In [136]:
X_emb[0]

array([ 0.08800655, -0.07521948, -0.10130121,  0.05293746,  0.05003943,
       -0.05716847,  0.01959494,  0.05139431, -0.18669316,  0.33456149,
        0.0689056 ,  0.12638949, -0.08349783, -0.03352555,  0.03779771,
        0.02226598])

In [137]:
query = 'I just singned up. Is it too late to join the course?'

Q = cv.transform([query])
Q_emb = svd.transform(Q)

In [138]:
Q_emb[0]

array([ 0.04353868, -0.03070793, -0.04446496,  0.01264906,  0.02439195,
       -0.04987792,  0.01011172,  0.02979657, -0.10906788,  0.18118828,
        0.04715375,  0.08795165, -0.05782741, -0.00257914,  0.02309559,
       -0.00598159])

In [139]:
np.dot(X_emb[0], Q_emb[0])

np.float64(0.11811787788053049)

In [140]:
score = cosine_similarity(X_emb, Q_emb).flatten()

In [141]:
idx = np.argsort(-score)[:10]

In [142]:
list(df.loc[idx].text)

['If you have submitted two projects (and peer-reviewed at least 3 course-mates’ projects for each submission), you will get the certificate for the course. According to the course coordinator, Alexey Grigorev, only two projects are needed to get the course certificate.\n(optional) David Odimegwu',
 'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.',
 'Yes, we will keep all the materials after the course finishes, so you can follow the course at your own pace after it finishes.\nYou can also continue looking at the homeworks and continue preparing for the next cohort. I guess you can also start working on your final capstone project.',
 'No, late submissions are not 

In [143]:
from sklearn.decomposition import NMF

In [144]:
nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb

/home/codespace/.local/lib/python3.12/site-packages/sklearn/decomposition/_nmf.py:1742: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00939675,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.0050676 , 0.13877346, 0.        , ..., 0.        , 0.        ,
        0.01199712],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0180589 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.01995629]], shape=(948, 16))

In [145]:
Q = cv.transform([query])
Q_emb = nmf.transform(Q)
Q_emb[0]

array([0.        , 0.0010636 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.17482696,
       0.        , 0.        , 0.        , 0.00054511, 0.        ,
       0.        ])

In [146]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
list(df.loc[idx].text)

["The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
 "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
 'Yes, you can. You won’t be able to submit some of the homeworks, but you can still take part in the course.\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers’ Projects by the deadline. It means that if you join the course at the end of November and manage to work on 